import Head from 'next/head'
import Login from '../components/Login';
import Sidebar from '../components/Sidebar';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Chats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
    </div>
  )
}
